### ISSUE TITLE
Run tronitor as local user

### ISSUE THREAD

**Issue by jordantrizz** [christronyxyocum/tronitor#41]
Just wondering if it's possible? I haven't gone through the code deep enough to figure out why your require it aside from getting access to /tmp

Just about to create my first monitor from the command line! Liking it so far!

**Comment by christronyxyocum** [comment]
Yes, but it requires sudo, as shown in the README.md.

**Comment by jordantrizz** [comment]
Thanks for the reply, any plans to not require sudo/root for normal operation or a means to set the /tmp directoy? Once the required dependencies are installed and a temporary space is allocated, there shouldn't be a need for the script to do anything as root.

**Comment by christronyxyocum** [comment]
You can already set the temp directory that is used by editing the script. It's line 25. You can also comment out any functions you don't want to run, like the sudo check, package checks, etc. I haven't touched the script in a long time and, honestly, if I did, I would need a decent amount of motivation because I already should rewrite a lot of it.

**Comment by jordantrizz** [comment]
Thanks for putting the effort in, it's appreciated! If I submit pull requests, would you be willing to apply them? Obviously I expect a harsh review.

**Comment by christronyxyocum** [comment]
Thank you. There are harsh syntax checks, unit tests, and code coverage checks in place before merges happen, but yes, I'd be willing to, at the very least, review them.

**Comment by christronyxyocum** [comment]
So, I was confusing this and another project. Tronitor does not prompt to install packages so, I believe, the ONLY thing "requiring" the use of sudo would be writing to the temp dir. Using a non-root user, I cloned the repo, created a new dir, set the temp dir to that, and am able to run the script without sudo. I'm going to ditch the root check from the script and set the same temp dir to something else. I will be pushing to the development branch shortly so feel free to test that.

**Comment by christronyxyocum** [comment]
Checks are currently running so I'll let you know when you can test it.

**Comment by christronyxyocum** [comment]
Okay, all tests passed and everything is looking great. Let me know once you've done some testing and, if you think it all looks good, I'll merge into master.

**Comment by christronyxyocum** [comment]
Well, since all unit tests passed without any issues while not using sudo, I'm considering it a success, closing this, and merging everything in master.
