### ISSUE TITLE
Calling script with >/dev/null fails with "(23) Failed writing body"

### ISSUE THREAD

**Issue by Flip76** [christronyxyocum/tronitor#52]
**Describe the issue/bug**
I trying to run the script from crontab. Calling script with >/dev/null fails with "(23) Failed writing body". My crontab:
0 2 * * * backup /opt/tronitor/tronitor.sh -m UptimeRobot -p 12345678,12345679 >/dev/null 2>&1 

**To Reproduce**
./tronitor.sh -m UptimeRobot -p 12345678,12345679 >/dev/null

**Expected behavior**
Script should be able to run through and set all coma-seperated monitors to pause/unpause. I guess it's because the CURL-call. Another option would be to implement a "silent"-option

**Actual behavior**
Currently only the 1st monitor passed (12345678) will be paused

**Comment by christronyxyocum** [comment]
It's something to do with the use of JQ and possibly its output, which is why I created the ability to set JQ to true or false in the script, and also why I included a mention of that on the readme.

**Comment by Flip76** [comment]
You are absolutely right! Sorry for the confusion!
